# Generated by Django 3.0.4 on 2020-03-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_price', models.FloatField()),
                ('asset_details', models.CharField(max_length=500)),
                ('asset_bought_date', models.DateField()),
                ('asset_rate_of_return', models.FloatField()),
                ('asset_market_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=200)),
                ('tenant_address', models.CharField(blank=True, max_length=300, null=True)),
                ('tenant_identity', models.IntegerField(blank=True, null=True)),
                ('tenant_date_of_birth', models.DateField(blank=True, null=True)),
                ('tenant_profession', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant_photo', models.URLField(blank=True, max_length=500, null=True)),
                ('tenant_active', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_partial_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_asset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildingBlocks.Asset')),
                ('payment_tenant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildingBlocks.Tenant')),
            ],
        ),
    ]
