# Generated by Django 3.0.4 on 2020-03-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_asset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildingBlocks.Asset')),
                ('rent_tenant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildingBlocks.Tenant')),
            ],
        ),
    ]
