# Generated by Django 3.0.4 on 2020-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0002_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_source', models.CharField(max_length=500)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_interest', models.DecimalField(decimal_places=2, max_digits=3)),
                ('debt_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_emi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
