# Generated by Django 3.0.4 on 2020-03-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0003_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debt_interest',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
