# Generated by Django 3.0.4 on 2020-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0004_auto_20200317_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_bought', models.BooleanField(default=False)),
            ],
        ),
    ]
