# Generated by Django 3.0.4 on 2020-03-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0006_golditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=500)),
                ('card_last_digits', models.IntegerField()),
                ('card_expiry', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='golditem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_card_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildingBlocks.CreditCard')),
            ],
        ),
    ]
