# Generated by Django 3.0.4 on 2020-03-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0007_auto_20200318_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_name',
            field=models.CharField(max_length=30),
        ),
    ]
