# Generated by Django 3.0.4 on 2020-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0008_auto_20200319_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_details', models.CharField(max_length=500)),
                ('task_priority', models.CharField(choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'urgent')], max_length=20)),
                ('task_status', models.CharField(choices=[(0, 'not started'), (1, 'started'), (2, 'differed'), (3, 'complete')], max_length=20)),
            ],
        ),
    ]
