# Generated by Django 3.0.4 on 2020-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0009_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'urgent')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(0, 'not started'), (1, 'started'), (2, 'differed'), (3, 'complete')]),
        ),
    ]
