# Generated by Django 3.0.4 on 2020-03-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingBlocks', '0010_auto_20200320_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=300)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=300)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_expense_name', models.CharField(max_length=300)),
                ('r_expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('r_expense_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_income_name', models.CharField(max_length=300)),
                ('r_income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('r_income_date', models.DateField()),
            ],
        ),
    ]
